.TH "alphabetaia.h" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alphabetaia.h \- : Défini \fBAlphaBetaIA\fP une \fBIA\fP basée sur l'algorithme AlphaBeta  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'minmaxia\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlphaBetaIA\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
: Défini \fBAlphaBetaIA\fP une \fBIA\fP basée sur l'algorithme AlphaBeta 

Pour plus d'explication sur l'algorithme suivez ce lien : https://fr.wikipedia.org/wiki/%C3%89lagage_alpha-b%C3%AAta 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
