.TH "Console" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBgotoLigCol\fP (int lig, int col)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "int \fBkbhit\fP ()"
.br
.ti -1c
.RI "int \fBgetch\fP ()"
.br
.ti -1c
.RI "void \fBsetColor\fP (Color front=COLOR_DEFAULT, Color back=COLOR_DEFAULT_BACK)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
