.TH "etat.h" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
etat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'pion\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEtat\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
La structure \fBEtat\fP \&.\&.\&. Représente l'état actuel du jeu, utile pour les sauvegardes, (un historique ?) mais surtout pour l'\fBIA\fP !
.PP
Vous faites ce que vous voulez \&.\&.\&. mais l'\fBIA\fP prendra cette structure en entrée ! 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
