.TH "Jeu" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Jeu \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de QMainWindow\&.
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBfin_jeu\fP (COULEUR gagnant)"
.br
.ti -1c
.RI "void \fBchg_joueur\fP (COULEUR joueur)"
.br
.ti -1c
.RI "void \fBchg_score\fP (int blanc, int noir)"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBJeu\fP (QWidget *parent=nullptr)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
