.TH "MemIA" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemIA \- Hérite de la classe \fBAlphaBetaIA\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memia\&.h>\fP
.PP
Est dérivée de \fBAlphaBetaIA\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMemIA\fP (std::string const &fichier, unsigned prof, COULEUR c)"
.br
.ti -1c
.RI "virtual std::string \fBid\fP () const override"
.br
.RI "\fIIdentifiant de l'\fBIA\fP : 'alphabeta'\&. \fP"
.ti -1c
.RI "virtual \fBPion\fP \fBjouer\fP (\fBEtat\fP plateau) override"
.br
.RI "\fIEntrée de l'\fBIA\fP : lance l'execution de l'algorithme\&. \fP"
.ti -1c
.RI "void \fBgagne\fP ()"
.br
.RI "\fIIncrémentation de la valeur du noeud\&. \fP"
.ti -1c
.RI "void \fBperdu\fP ()"
.br
.RI "\fIdécrémentation de la valeur du noeud \fP"
.ti -1c
.RI "void \fBset_prof\fP (unsigned prof)"
.br
.RI "\fIModifie la profondeur de recherche\&. \fP"
.ti -1c
.RI "void \fBset_noeud\fP (int pos)"
.br
.RI "\fIModifie le noeud actuel du \fBMemIA\fP\&. \fP"
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Hérite de la classe \fBAlphaBetaIA\fP\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
