.TH "Menu" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "int \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBafficher\fP ()"
.br
.ti -1c
.RI "COULEUR \fBchoix_coul\fP () const "
.br
.ti -1c
.RI "void \fBregles\fP () const "
.br
.ti -1c
.RI "bool \fBcharger\fP (\fBTableau\fP &tab, bool &memia_noire, bool &memia_blanche) const "
.br
.ti -1c
.RI "void \fBparams\fP ()"
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static void \fBentete\fP ()"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
