.TH "Tableau" 3 "Dimanche 23 Avril 2017" "othello" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tableau \- Hérite de la classe console\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plateau\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBTableau\fP (std::shared_ptr< \fBIA\fP > ia_noir=nullptr, std::shared_ptr< \fBIA\fP > ia_blanc=nullptr)"
.br
.ti -1c
.RI "\fBTableau\fP (\fBEtat\fP &&etat, std::shared_ptr< \fBIA\fP > ia_noir, std::shared_ptr< \fBIA\fP > ia_blanc)"
.br
.ti -1c
.RI "void \fBCreationTab\fP ()"
.br
.RI "\fICréation de la structure du tableau\&. \fP"
.ti -1c
.RI "bool \fBJouer\fP (int &x, int &y)"
.br
.RI "\fIPermet le déplacement des pions et la pose d'un pion\&. \fP"
.ti -1c
.RI "void \fBAfficherTab\fP ()"
.br
.RI "\fIPermet de choisir la couleur des cases, quand elles sont vides ou avec un pion\&. \fP"
.ti -1c
.RI "COULEUR \fBBoucleJeu\fP ()"
.br
.RI "\fIPermet la permutation des joueurs, affiche le score des joueurs\&. \fP"
.ti -1c
.RI "bool \fBsauvegarder\fP () const "
.br
.RI "\fISauvegarde de la partie\&. \fP"
.ti -1c
.RI "std::map< COULEUR, unsigned > const \fBscores\fP () const "
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBPion\fP > > const & \fBget_pions\fP () const "
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBConsole\fP * \fBs_console\fP = NULL"
.br
.RI "\fIPointeur sur console initialisé à NULL\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Hérite de la classe console\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour othello à partir du code source\&.
